<?xml version="1.0"?>
<package format="3">
  <name>f9p_bringup</name>
  <version>1.0.0</version>
  <description>Package for F9P-RTK and ZED2i cameras running on CPU</description>
  <maintainer email="vinicius.m.souza@tecnico.ulisboa.pt">viniciusmenesessouza</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <depend>libhidapi-dev</depend>
  <depend>libopencv-dev</depend>
  <depend>libusb-1.0-dev</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>roscpp</depend>

</package>
